service: laravel-api

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  environment:
    APP_ENV: production
    APP_DEBUG: 0
    DB_CONNECTION: mysql
    DB_HOST: caboose.proxy.rlwy.net
    DB_PORT: 3306
    DB_DATABASE: railway
    DB_USERNAME: root
    DB_PASSWORD: WkhwfjkaRoCrMzVepHTpxQcSKNTrZEdh

plugins:
  - ./vendor/bref/bref

functions:
  api:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-82-fpm}
